config/routes.rb
Rails.application.routes.draw do
# 会員側
  get 'homes/top'
  devise_for :customers, controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'orders/complete' => 'orders#complete'
  resources :items
  resources :orders
  post '/orders/confirm' => 'orders#confirm'
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items
  resources :shipping_addresses
  resources :customers
  # 退会確認画面
  get '/customer/:id/quit' => 'customers#quit', as: 'quit'
  # 論理削除用のルーティング
  patch '/customer/:id/withdraw' => 'customers#withdraw', as: 'withdraw'

  get 'search/search'
  get '/search', to: 'search#search'

# 管理側
  devise_for :admins, controllers: {
        sessions: 'admins/sessions',
        registrations: 'admins/registrations'
      }

  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :genres
    resources :orders
    resources :order_details, only:[:update]
    resources :items
    resources :customers
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中:3, 発送済み:4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

  belongs_to :customer
  has_many :order_details

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.page(params[:page]).per(10)
    #@order_details = OrderDetail.where(order_id: @order.id)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.order_status == "入金確認"
      @order_details.update(making_status: 1)
    end
      redirect_to request.referer
  end

  private

  def order_params
    params.require(:order).permit(:payment_method,:postal_code,:address,:name,:shipping_cost,:total_payment,:order_status)
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index #注文履歴画面
   @orders = Order.where(customer_id: current_customer.id)
  # @order = @orders.current_customer.id
  # @order_details = OrderDetail.where(order_id: @order.id)
  end

  def show #注文履歴詳細画面
   @order = Order.find(params[:id])
   @order_details = OrderDetail.where(order_id: @order.id)
  end

  def new #注文情報入力画面
    @order = Order.new
    @customer = Customer.find(current_customer.id)
    @shipping_addresses = ShippingAddress.where(customer: current_customer)
  end

  def confirm #注文情報確認画面
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @cart_items = CartItem.where(customer_id: current_customer.id)
    if params[:order][:address_option].to_i == 0
      @customer = Customer.find(current_customer.id)
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name

    elsif params[:order][:address_option].to_i == 1
      @ship = ShippingAddress.find(params[:order][:shipping_address_id])
      @order.postal_code = @ship.postal_code
      @order.address = @ship.address
      @order.name = @ship.name

    elsif params[:order][:address_option].to_i == 2
      @order = Order.new(order_params)
    end
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.save

    @cart_items = CartItem.where(customer_id: current_customer.id)

    @cart_items.each do |cart_item|
      @order_details = OrderDetail.new
      @order_details.item_id = cart_item.item.id
      @order_details.order_id = @order.id
      @order_details.amount = cart_item.amount
      @order_details.price = cart_item.item.price
      @order_details.save
    end
    @cart_items.destroy_all
    redirect_to orders_complete_path
  end

  def complete #注文完了画面
  end

  private

  def order_params
    params.require(:order).permit(:payment_method,:postal_code,:address,:name,:shipping_cost,:total_payment,:order_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class = "container px-5 px-sm-0">
  <div class = "row">
    <div class = "col-md-8 offset-md-1">
      <div class = "col-3 my-5 title" >
      <h4>注文履歴一覧</h4>
      </div>
      <table class = "table table-bordered">
        <thead class="table-secondary">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to admin_order_path(order) do %>
                  <%= order.created_at.strftime('%Y/%m/%d') %>
                <% end %>
              </td>
              <td>
                <%= order.customer.last_name %><%= order.customer.first_name %>
              </td>
              <td>
                <%= order.order_details.sum(:amount) %>
              </td>
              <td>
                <%= order.order_status %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class = "container">
      <div class = "col-3 my-5 title" >
        <h4>注文履歴詳細</h4>
      </div>

      <table class="table table-borderless">
  <tr>
    <th>購入者</th>
    <td><%= link_to admin_customer_path(@order.customer) do %>
        <%= @order.customer.last_name %> <%= @order.customer.first_name %>
        <% end %></td>
    <td><td>
  </tr>

  <tr>
    <th>注文日</th>
    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    <td><td>
  </tr>

  <tr>
    <th>配送先</th>
    <td>〒 <%= @order.customer.postal_code %> <%= @order.customer.address %></td>
    <td><td>
  </tr>

  <tr>
    <th>支払方法</th>
    <td><%= @order.payment_method %></td>
    <td><td>
  </tr>

  <tr>
    <th>注文ステータス</th>
    <td>
      <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
      <%= f.select :order_status, Order.order_statuses.keys %>
      <%= f.submit "更新", class: "btn btn-success" %>
      <% end %>
    </td>
  </tr>
      </table>


      <table class = "table" >
        <thead>
          <tr>
            <th class="table-secondary">商品名</th>
            <th class="table-secondary">単価（税込）</th>
            <th class="table-secondary">数量</th>
            <th class="table-secondary">小計</th>
            <th class="table-secondary">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= (order_detail.item.price.to_i * 1.1).floor.to_s(:delimited) %>円</td>
              <td><%= order_detail.amount %></td>
              <td><%= ((order_detail.item.price.to_i * 1.1) * order_detail.amount.to_i).floor.to_s(:delimited) %>円</td>

              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f| %>
              <td><%= f.select :making_status, OrderDetail.making_statuses.keys %>
              <%= f.submit "更新", class: "btn btn-success" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

</div>