config/routes.rb
Rails.application.routes.draw do
# 会員側
  get 'homes/top'
  devise_for :customers, controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'orders/complete' => 'orders#complete'
  resources :items
  resources :orders
  post '/orders/confirm' => 'orders#confirm'
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items
  resources :shipping_addresses
  resources :customers
  # 退会確認画面
  get '/customer/:id/quit' => 'customers#quit', as: 'quit'
  # 論理削除用のルーティング
  patch '/customer/:id/withdraw' => 'customers#withdraw', as: 'withdraw'

  get 'search/search'
  get '/search', to: 'search#search'

# 管理側
  devise_for :admins, controllers: {
        sessions: 'admins/sessions',
        registrations: 'admins/registrations'
      }

  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :genres
    resources :orders
    resources :order_details, only:[:update]
    resources :items
    resources :customers
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :orders
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)

  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    if @customer.save
      flash[:notice] = "You have updted customer successfully."
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

    private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:kana_last_name,:kana_first_name,:postal_code,:address,:phone_number,:email,:is_deleted)
  end


end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
   customer_path(current_customer.id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  protected

  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_user
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to homes_top_path
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end


  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if  @customer.update(customer_params)
        flash[:notice] = "You have updated  successfully."
        redirect_to customer_path(@customer)
    else
        render :edit
    end
  end

  def quit
  end


  def withdraw
    @customer = Customer.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会しました。ありがとうございました。またの、ご利用をお持ちしております"
    redirect_to root_path
  end


  private

  def customer_params
	  params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email, :postal_code, :address, :phone_number, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container">
  
  <div class = "col-2 my-5 title" >
    <h4>会員情報編集</h4>
  </div>

<%= form_with model: @customer, url: customer_path, local:true do |f| %>

  <table class="table table-borderless">
    <tr>
      <th><%= f.label :氏名 %></th>
      <td><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>&emsp;
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %></td>
    </tr>
    <tr>
      <th><%= f.label :フリガナ %></th>
      <td><%= f.text_field :kana_last_name, autofocus: true, autocomplete: "kana_last_name" %>&emsp;
          <%= f.text_field :kana_first_name, autofocus: true, autocomplete: "kana_first_name" %></td>
    </tr>
    <tr>
      <th><%= f.label :郵便番号 %></th>
      <td><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %></td>
    </tr>
    <tr>
      <th><%= f.label :住所 %></th>
      <td><%= f.text_field :address, autofocus: true, autocomplete: "address" ,:size => "70*70" %></td>
    </tr>
    <tr>
      <th><%= f.label :電話番号 %></th>
      <td><%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number" %></td>
    </tr>
    <tr>
      <th><%= f.label :メールアドレス %></th>
      <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <div class="actions">
          <%= f.submit "編集内容を保存" ,class:"btn btn-success" %>&emsp;&emsp;&emsp;<%= link_to "退会する" ,quit_path ,class:"btn btn-danger" %>
        </div>
      </td>
    </tr>
  </table>
<% end %>
</div>

app/views/customers/quit.html.erb
<div class="container">
    <h1 class="my-3 h3"></h1>
    <div class="d-flex align-items-center justify-content-center" style="height:120px;">
        <div class="row">
            <h4><strong>本当に退会しますか？</strong></h4>
        </div>
    </div>

    <div class="d-flex align-items-center justify-content-center">
        <div class="row">
            <p>退会すると、会員登録情報や</p>
        </div>
    </div>

    <div class="d-flex align-items-center justify-content-center">
        <div class="row">
            <p>これまでの購⼊履歴が閲覧できなくなります。</p>
        </div>
    </div>

    <div class="d-flex align-items-center justify-content-center">
        <div class="row">
            <p>退会する場合は、「退会する」をクリックしてください。</p>
        </div>
    </div>


    <div class="d-flex align-items-center justify-content-center" style="height:125px;">
        <div class="row">
        <div class="mx-3"><%= link_to '退会しない', customer_path, class: "btn btn-primary" %></div>
        <div class="mx-3"><%= link_to "退会する", withdraw_path, method: :patch, data: { confilm: "本当に退会しますか？" }, class: "btn btn-danger" %></div>
        </div>
    </div>
</div>

app/views/customers/show.html.erb
<div class="container">

<div class = "col-2 my-5 title" >
<h4>マイページ</h4>
</div>

<div class="firld_group">
  <p><strong>登録情報 </strong>&emsp;<%= link_to "編集する", edit_customer_path, class: "btn btn-success" %></p>
</div>

<table class="table table-bordered">
  <tbody>
    <tr>
      <td class="table-secondary">氏名 </td>
      <td><%= @customer.last_name %> <%= @customer.first_name %></td>
    </tr>
    <tr>
      <td class="table-secondary">カナ </td>
      <td><%= @customer.kana_last_name %> <%= @customer.kana_first_name %></td>
    </tr>
    <tr>
      <td class="table-secondary">郵便番号 </td>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <td class="table-secondary">住所 </td>
      <td><%= @customer.address %> </td>
    </tr>
    <tr>
      <td class="table-secondary">電話番号 </td>
      <td><%= @customer.phone_number %> </td>
    </tr>
    <tr>
      <td class="table-secondary">メールアドレス </td>
      <td><%= @customer.email %> </td>
    </tr>
  </tbody>
</table>

 <div class="row my-3">
   <div class="col-2">
   <strong>配送先</strong>
   </div>
   <%= link_to "一覧を見る", shipping_addresses_path, class: "btn btn-primary" %>

</div>

 <div class="row">
   <div class="col-2">
    <strong>注文履歴</strong>
    </div>
   <%= link_to "一覧を見る", orders_path, class: "btn btn-primary" %>

</div>
</div>