config/routes.rb
Rails.application.routes.draw do
# 会員側
  get 'homes/top'
  devise_for :customers, controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'orders/complete' => 'orders#complete'
  resources :items
  resources :orders
  post '/orders/confirm' => 'orders#confirm'
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items
  resources :shipping_addresses
  resources :customers
  # 退会確認画面
  get '/customer/:id/quit' => 'customers#quit', as: 'quit'
  # 論理削除用のルーティング
  patch '/customer/:id/withdraw' => 'customers#withdraw', as: 'withdraw'

  get 'search/search'
  get '/search', to: 'search#search'

# 管理側
  devise_for :admins, controllers: {
        sessions: 'admins/sessions',
        registrations: 'admins/registrations'
      }

  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :genres
    resources :orders
    resources :order_details, only:[:update]
    resources :items
    resources :customers
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :orders
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :name, presence: true
  validates :name, length: { maximum: 20 }
end

app/models/item.rb
class Item < ApplicationRecord


  before_save :set_tax_price
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  attachment :image

  private

  def set_tax_price
    price * 1.10
  end


end

app/models/order.rb
class Order < ApplicationRecord

  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中:3, 発送済み:4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

  belongs_to :customer
  has_many :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了:3 }
  belongs_to :order
  belongs_to :item

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  
  belongs_to :customer
  
  def order_address
			self.postal_code + self.address + self.name
	end
  
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart_items = CartItem.where(customer_id: current_customer.id)
  end

  def update
    @cart_items = CartItem.find(params[:id])
    @cart_items.update(cart_item_params)
    redirect_to request.referer
  end

  def create
    @cart_items = CartItem.new(cart_item_params)
    @cart_items.customer_id = current_customer.id
    if
     @cart_items.save
     redirect_to cart_items_path
    else
     redirect_to request.referer
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
		@cart_item.destroy
		redirect_to cart_items_path
  end

  def destroy_all
    @cart_items = CartItem.where(customer_id: current_customer.id)
    @cart_items.destroy_all
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:amount,:item_id)
  end


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if  @customer.update(customer_params)
        flash[:notice] = "You have updated  successfully."
        redirect_to customer_path(@customer)
    else
        render :edit
    end
  end

  def quit
  end


  def withdraw
    @customer = Customer.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会しました。ありがとうございました。またの、ご利用をお持ちしております"
    redirect_to root_path
  end


  private

  def customer_params
	  params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email, :postal_code, :address, :phone_number, :is_deleted)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all.order(id: "DESC").limit(4)
  end
  
  def about
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(8)
    @item_amount = Item.count
    @genres = Genre.all
    @genre = 0
  end

  def show
    @item = Item.find(params[:id])
    @cart_items = CartItem.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index #注文履歴画面
   @orders = Order.where(customer_id: current_customer.id)
  # @order = @orders.current_customer.id
  # @order_details = OrderDetail.where(order_id: @order.id)
  end

  def show #注文履歴詳細画面
   @order = Order.find(params[:id])
   @order_details = OrderDetail.where(order_id: @order.id)
  end

  def new #注文情報入力画面
    @order = Order.new
    @customer = Customer.find(current_customer.id)
    @shipping_addresses = ShippingAddress.where(customer: current_customer)
  end

  def confirm #注文情報確認画面
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @cart_items = CartItem.where(customer_id: current_customer.id)
    if params[:order][:address_option].to_i == 0
      @customer = Customer.find(current_customer.id)
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name

    elsif params[:order][:address_option].to_i == 1
      @ship = ShippingAddress.find(params[:order][:shipping_address_id])
      @order.postal_code = @ship.postal_code
      @order.address = @ship.address
      @order.name = @ship.name

    elsif params[:order][:address_option].to_i == 2
      @order = Order.new(order_params)
    end
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.save

    @cart_items = CartItem.where(customer_id: current_customer.id)

    @cart_items.each do |cart_item|
      @order_details = OrderDetail.new
      @order_details.item_id = cart_item.item.id
      @order_details.order_id = @order.id
      @order_details.amount = cart_item.amount
      @order_details.price = cart_item.item.price
      @order_details.save
    end
    @cart_items.destroy_all
    redirect_to orders_complete_path
  end

  def complete #注文完了画面
  end

  private

  def order_params
    params.require(:order).permit(:payment_method,:postal_code,:address,:name,:shipping_cost,:total_payment,:order_status)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @genre = Genre.find(params[:genre_id])
    @items = @genre.items.page(params[:page]).per(8)
    @item_amount = @items.count
    @genres = Genre.all
    render 'items/index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/cart_items/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-3 my-5 title" >
      <h4>ショッピングカート</h4>
    </div>
  </div>
  <div class = "row" style = "height:50px">
    <div class = "offset-10">
      <%= link_to 'カートを空にする', cart_items_destroy_all_path, class: 'btn-sm btn-danger', method: :delete %>
    </div>
  </div>

  <div class = "row">
    <table class = "table table-bordered" >

      <thead>
        <tr>
          <th class="table-secondary">商品名</th>
          <th class="table-secondary">単価（税込）</th>
          <th class="table-secondary">数量</th>
          <th class="table-secondary">小計</th>
          <th class="table-secondary"></th>
        </tr>
      </thead>

      <tbody>
        <% sum = 0 %>
        <% @cart_items.each do |cart_item| %>
          <tr>
            <th><%= attachment_image_tag cart_item.item, :image, size: "60x40" %><%= cart_item.item.name %></th>
            <th>¥<%= (cart_item.item.price.to_i * 1.1).floor.to_s(:delimited) %></th>
            <th>
              <%= form_with url: cart_item_path(cart_item.id), model: cart_item, local: true do |f| %>
                <%= f.select :amount, [1,2,3,4,5,6,7,8,9,10], class: 'form-control' %>
                <%= f.submit "変更", class: "btn-sm btn-success" %>
              <% end %>
            </th>
            <th>¥<%= ((cart_item.item.price.to_i * 1.1).floor * cart_item.amount.to_i).to_s(:delimited) %></th>
            <th><%= link_to " 削除 ", cart_item_path(cart_item.id), class: 'btn-sm btn-danger', method: :delete %></th>
          </tr>
          <% sum += (cart_item.item.price.to_i * 1.1).floor * cart_item.amount.to_i %>
        <% end %>
      </tbody>

    </table>
  </div>

  <div class = "row mt-5" style = "height:100px">
    <div class = "col-2">
      <%= link_to "買い物を続ける", root_path, class: 'btn btn-primary' %>
    </div>
    <div class = "col-4 offset-4">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th class="table-secondary">合計</th><th class = "text-right">¥<%= sum.to_s(:delimited) %></th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class = "row">
    <div class = "mx-auto">
      <%= link_to "情報入力に進む", new_order_path, class: "btn btn-success" %>
    </div>
  </div>

</div>