config/routes.rb
Rails.application.routes.draw do
# 会員側
  get 'homes/top'
  devise_for :customers, controllers: {
        sessions: 'customers/sessions',
        registrations: 'customers/registrations'
      }

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'orders/complete' => 'orders#complete'
  resources :items
  resources :orders
  post '/orders/confirm' => 'orders#confirm'
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items
  resources :shipping_addresses
  resources :customers
  # 退会確認画面
  get '/customer/:id/quit' => 'customers#quit', as: 'quit'
  # 論理削除用のルーティング
  patch '/customer/:id/withdraw' => 'customers#withdraw', as: 'withdraw'

  get 'search/search'
  get '/search', to: 'search#search'

# 管理側
  devise_for :admins, controllers: {
        sessions: 'admins/sessions',
        registrations: 'admins/registrations'
      }

  namespace :admin do
    get 'homes/top' => 'homes#top'
    resources :genres
    resources :orders
    resources :order_details, only:[:update]
    resources :items
    resources :customers
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :orders
  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :name, presence: true
  validates :name, length: { maximum: 20 }
end

app/models/item.rb
class Item < ApplicationRecord


  before_save :set_tax_price
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  attachment :image

  private

  def set_tax_price
    price * 1.10
  end


end

app/models/order.rb
class Order < ApplicationRecord

  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中:3, 発送済み:4 }
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

  belongs_to :customer
  has_many :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了:3 }
  belongs_to :order
  belongs_to :item

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  
  belongs_to :customer
  
  def order_address
			self.postal_code + self.address + self.name
	end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all.order(id: "DESC").limit(4)
  end
  
  def about
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(8)
    @item_amount = Item.count
    @genres = Genre.all
    @genre = 0
  end

  def show
    @item = Item.find(params[:id])
    @cart_items = CartItem.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index #注文履歴画面
   @orders = Order.where(customer_id: current_customer.id)
  # @order = @orders.current_customer.id
  # @order_details = OrderDetail.where(order_id: @order.id)
  end

  def show #注文履歴詳細画面
   @order = Order.find(params[:id])
   @order_details = OrderDetail.where(order_id: @order.id)
  end

  def new #注文情報入力画面
    @order = Order.new
    @customer = Customer.find(current_customer.id)
    @shipping_addresses = ShippingAddress.where(customer: current_customer)
  end

  def confirm #注文情報確認画面
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @cart_items = CartItem.where(customer_id: current_customer.id)
    if params[:order][:address_option].to_i == 0
      @customer = Customer.find(current_customer.id)
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name

    elsif params[:order][:address_option].to_i == 1
      @ship = ShippingAddress.find(params[:order][:shipping_address_id])
      @order.postal_code = @ship.postal_code
      @order.address = @ship.address
      @order.name = @ship.name

    elsif params[:order][:address_option].to_i == 2
      @order = Order.new(order_params)
    end
  end

  def create
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.save

    @cart_items = CartItem.where(customer_id: current_customer.id)

    @cart_items.each do |cart_item|
      @order_details = OrderDetail.new
      @order_details.item_id = cart_item.item.id
      @order_details.order_id = @order.id
      @order_details.amount = cart_item.amount
      @order_details.price = cart_item.item.price
      @order_details.save
    end
    @cart_items.destroy_all
    redirect_to orders_complete_path
  end

  def complete #注文完了画面
  end

  private

  def order_params
    params.require(:order).permit(:payment_method,:postal_code,:address,:name,:shipping_cost,:total_payment,:order_status)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @genre = Genre.find(params[:genre_id])
    @items = @genre.items.page(params[:page]).per(8)
    @item_amount = @items.count
    @genres = Genre.all
    render 'items/index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Nagano Cake</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>

                <li class="nav-item">
                 <p class="nav-link text-light">ようこそ<%= current_customer.last_name %>さん！</p>
                </li>

                 <li class="nav-item">
                  <%= link_to "マイページ", customer_path(current_customer.id), class: 'nav-link text-light' %>
                </li>

                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "カート一覧", cart_items_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-light' %>
                </li>

              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_orders_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
                </li>

              <% else %>
                 <li class="nav-item">
                  <%= link_to "About", home_about_path, class: 'nav-link text-light' %>
                </li>
                 <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path, class: "nav-link text-light" %>
                </li>
                 <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path, class: "nav-link text-light" %>
                </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratot.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>